version: "3.4"
services:
  
  elapi:
    build: .
    ports:
    - "8080:80"
    environment: 
      URL_DATABASE: elserver
      HOST_DATABASE: ozona
      USER_DATABASE: root
      PASSWORD_DATABASE: abc123.
    links: 
      - elserver:elserver

    
  elserver:
    image: mysql:8.0.13
    #restart: always
    environment:
      MYSQL_USER: practica
      MYSQL_PASSWORD: abc123.
      MYSQL_ROOT_PASSWORD: abc123.
      MYSQL_DATABASE: ozona
    volumes:
      - ~/docker/mysql-data:/var/lib/mysql


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200


  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200    # address of elasticsearch docker container which kibana will connect
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch 


volumes:
    elasticsearch-data-volume:
      driver: local