kind: Service
apiVersion: v1
metadata:
  name: elserver
  labels:
      app: elserver
spec:
  type: ClusterIP
  selector:
    app: elserver
    tier: elserver
    ClusterIP: None
  ports:
  - port: 3306
    targetPort: 3306
    